/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as IncomesRouteImport } from './routes/incomes'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DebtsRouteImport } from './routes/debts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEmailInboundRouteImport } from './routes/api/email/inbound'
import { Route as ApiEmailBackfillRouteImport } from './routes/api/email/backfill'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiEmailGmailWebhookRouteImport } from './routes/api/email/gmail/webhook'
import { Route as ApiEmailGmailWatchRouteImport } from './routes/api/email/gmail/watch'
import { Route as ApiEmailGmailSyncRouteImport } from './routes/api/email/gmail/sync'
import { Route as ApiEmailGmailPollRouteImport } from './routes/api/email/gmail/poll'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomesRoute = IncomesRouteImport.update({
  id: '/incomes',
  path: '/incomes',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtsRoute = DebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailInboundRoute = ApiEmailInboundRouteImport.update({
  id: '/api/email/inbound',
  path: '/api/email/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailBackfillRoute = ApiEmailBackfillRouteImport.update({
  id: '/api/email/backfill',
  path: '/api/email/backfill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailGmailWebhookRoute = ApiEmailGmailWebhookRouteImport.update({
  id: '/api/email/gmail/webhook',
  path: '/api/email/gmail/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailGmailWatchRoute = ApiEmailGmailWatchRouteImport.update({
  id: '/api/email/gmail/watch',
  path: '/api/email/gmail/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailGmailSyncRoute = ApiEmailGmailSyncRouteImport.update({
  id: '/api/email/gmail/sync',
  path: '/api/email/gmail/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailGmailPollRoute = ApiEmailGmailPollRouteImport.update({
  id: '/api/email/gmail/poll',
  path: '/api/email/gmail/poll',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debts': typeof DebtsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goals': typeof GoalsRoute
  '/incomes': typeof IncomesRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/email/backfill': typeof ApiEmailBackfillRoute
  '/api/email/inbound': typeof ApiEmailInboundRoute
  '/api/email/gmail/poll': typeof ApiEmailGmailPollRoute
  '/api/email/gmail/sync': typeof ApiEmailGmailSyncRoute
  '/api/email/gmail/watch': typeof ApiEmailGmailWatchRoute
  '/api/email/gmail/webhook': typeof ApiEmailGmailWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debts': typeof DebtsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goals': typeof GoalsRoute
  '/incomes': typeof IncomesRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/email/backfill': typeof ApiEmailBackfillRoute
  '/api/email/inbound': typeof ApiEmailInboundRoute
  '/api/email/gmail/poll': typeof ApiEmailGmailPollRoute
  '/api/email/gmail/sync': typeof ApiEmailGmailSyncRoute
  '/api/email/gmail/watch': typeof ApiEmailGmailWatchRoute
  '/api/email/gmail/webhook': typeof ApiEmailGmailWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debts': typeof DebtsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goals': typeof GoalsRoute
  '/incomes': typeof IncomesRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/email/backfill': typeof ApiEmailBackfillRoute
  '/api/email/inbound': typeof ApiEmailInboundRoute
  '/api/email/gmail/poll': typeof ApiEmailGmailPollRoute
  '/api/email/gmail/sync': typeof ApiEmailGmailSyncRoute
  '/api/email/gmail/watch': typeof ApiEmailGmailWatchRoute
  '/api/email/gmail/webhook': typeof ApiEmailGmailWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debts'
    | '/forgot-password'
    | '/goals'
    | '/incomes'
    | '/investments'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/api/auth/$'
    | '/api/email/backfill'
    | '/api/email/inbound'
    | '/api/email/gmail/poll'
    | '/api/email/gmail/sync'
    | '/api/email/gmail/watch'
    | '/api/email/gmail/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debts'
    | '/forgot-password'
    | '/goals'
    | '/incomes'
    | '/investments'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/api/auth/$'
    | '/api/email/backfill'
    | '/api/email/inbound'
    | '/api/email/gmail/poll'
    | '/api/email/gmail/sync'
    | '/api/email/gmail/watch'
    | '/api/email/gmail/webhook'
  id:
    | '__root__'
    | '/'
    | '/debts'
    | '/forgot-password'
    | '/goals'
    | '/incomes'
    | '/investments'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/api/auth/$'
    | '/api/email/backfill'
    | '/api/email/inbound'
    | '/api/email/gmail/poll'
    | '/api/email/gmail/sync'
    | '/api/email/gmail/watch'
    | '/api/email/gmail/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebtsRoute: typeof DebtsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GoalsRoute: typeof GoalsRoute
  IncomesRoute: typeof IncomesRoute
  InvestmentsRoute: typeof InvestmentsRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiEmailBackfillRoute: typeof ApiEmailBackfillRoute
  ApiEmailInboundRoute: typeof ApiEmailInboundRoute
  ApiEmailGmailPollRoute: typeof ApiEmailGmailPollRoute
  ApiEmailGmailSyncRoute: typeof ApiEmailGmailSyncRoute
  ApiEmailGmailWatchRoute: typeof ApiEmailGmailWatchRoute
  ApiEmailGmailWebhookRoute: typeof ApiEmailGmailWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incomes': {
      id: '/incomes'
      path: '/incomes'
      fullPath: '/incomes'
      preLoaderRoute: typeof IncomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debts': {
      id: '/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof DebtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/inbound': {
      id: '/api/email/inbound'
      path: '/api/email/inbound'
      fullPath: '/api/email/inbound'
      preLoaderRoute: typeof ApiEmailInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/backfill': {
      id: '/api/email/backfill'
      path: '/api/email/backfill'
      fullPath: '/api/email/backfill'
      preLoaderRoute: typeof ApiEmailBackfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/gmail/webhook': {
      id: '/api/email/gmail/webhook'
      path: '/api/email/gmail/webhook'
      fullPath: '/api/email/gmail/webhook'
      preLoaderRoute: typeof ApiEmailGmailWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/gmail/watch': {
      id: '/api/email/gmail/watch'
      path: '/api/email/gmail/watch'
      fullPath: '/api/email/gmail/watch'
      preLoaderRoute: typeof ApiEmailGmailWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/gmail/sync': {
      id: '/api/email/gmail/sync'
      path: '/api/email/gmail/sync'
      fullPath: '/api/email/gmail/sync'
      preLoaderRoute: typeof ApiEmailGmailSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/gmail/poll': {
      id: '/api/email/gmail/poll'
      path: '/api/email/gmail/poll'
      fullPath: '/api/email/gmail/poll'
      preLoaderRoute: typeof ApiEmailGmailPollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebtsRoute: DebtsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GoalsRoute: GoalsRoute,
  IncomesRoute: IncomesRoute,
  InvestmentsRoute: InvestmentsRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiEmailBackfillRoute: ApiEmailBackfillRoute,
  ApiEmailInboundRoute: ApiEmailInboundRoute,
  ApiEmailGmailPollRoute: ApiEmailGmailPollRoute,
  ApiEmailGmailSyncRoute: ApiEmailGmailSyncRoute,
  ApiEmailGmailWatchRoute: ApiEmailGmailWatchRoute,
  ApiEmailGmailWebhookRoute: ApiEmailGmailWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
